name = "stun"
main = "_worker.js"
compatibility_date = "2026-06-19"
keep_vars = true

[[kv_namespaces]]
binding = "KV"
id = "dbcc7f7c702246998fff94c321f8d60f"

[vars]                                                                                                                                                                                                                                            
ADMIN = "6480789521"                                                                                                                                                                                                                              
UUID = "e82b6856-e4f7-4dba-8a0c-0e4a65ae54c9"

[placement]
mode = "smart"
